org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# AGP 8.9.1 官方支持至 compileSdk 36，升级 37 后压制提示（Android 17 已正式发布）
android.suppressUnsupportedCompileSdk=37
org.gradle.java.home=C:/Program Files/Zulu/zulu-17
